### ISSUE TITLE
postqf-0.5 fails under python 3.12.3 (Ubuntu 24.04)

### ISSUE THREAD

**Issue by dominicraf** [rseichter/postqf#4]
The suggested install with `pip` (or, rather, `pip3`) no longer works under Ubuntu 24.04 (Python 3.12.3) (though it may work with `pipx`, I have not tested). The alternative install works but when I use `postqf` I see (example):
```
# postqueue -j|postqf -q deferred -d 'connect to 127\.0\.0\.1\[127\.0\.0\.1\]:10024: Connection refused' -i
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/postqf/postqf-0.5/postqf/__main__.py", line 18, in <module>
    main()
  File "/root/postqf/postqf-0.5/postqf/core.py", line 205, in main
    process_files()
  File "/root/postqf/postqf-0.5/postqf/core.py", line 162, in process_files
    infile = open_file(path, 'rt', sys.stdin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/postqf/postqf-0.5/postqf/core.py", line 51, in open_file
    return open(path, mode=mode, encoding='utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'to'
```
Note that the postqueue was empty when this command was run. The problem does not appear with Ubuntu 22.04 (Python 3.10.12)

**Comment by rseichter** [comment]
Thanks for the report. Please describe in more detail how you went about installing postqf. Was it done as `root`, or as an unprivileged user? Did you use a clean Ubuntu installation, or were additional Python modules present?

**Comment by dominicraf** [comment]
It was an existing Ubuntu 22.04 machine that I upgraded to 24.04. Afterwards I found I had to reinstall postqf. I installed it as root using the alternative install and then created a symlink in /usr/local/bin.

It seems to be the space(s) in the -d string that cause the problem:
```
# postqueue -j|postqf -q deferred -d 'connect' -i
# postqueue -j|postqf -q deferred -d 'connect to' -i
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/postqf/postqf-0.5/postqf/__main__.py", line 18, in <module>
    main()
  File "/root/postqf/postqf-0.5/postqf/core.py", line 205, in main
    process_files()
  File "/root/postqf/postqf-0.5/postqf/core.py", line 162, in process_files
    infile = open_file(path, 'rt', sys.stdin)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/postqf/postqf-0.5/postqf/core.py", line 51, in open_file
    return open(path, mode=mode, encoding='utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'to'

```

**Comment by rseichter** [comment]
I have updated the [install script](https://github.com/rseichter/postqf/blob/master/scripts/install.sh) (please note the new .sh suffix) and fixed a quoting issue in the generated launcher script. That fixes the runtime problems in my tests. However, the part of no longer being able to install using `pip` remains. Did you do anything else except this:
```
(root) # pip install postqf
```
Resolving related problems in modern Python versions will probably require adding support for PEP 517 style builds, but I want to be certain I understand what trouble you encountered. You did not yet tell me how exactly pip "failed" for you. 😉

**Comment by dominicraf** [comment]
Thanks yes the amended script seems to work with spaces now.

Regarding pip:
```
# pip install postqf
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```
but this works ok:
`# pipx install postqf`

Thanks for your speedy assistance!

**Comment by rseichter** [comment]
Well, "externally managed environments" as Ubuntu calls them are outside of my control. I understand the need to protect systems against the shortcomings of `pip`, which is not a full-fledged package manager and lacks Python module isolation. Using virtual Python environments is one possible way to deal with this, and I often use this method myself.

I might document using Python's `venv` module as an alternative method of installation, but `postqf` does not require additional modules, which is where virtual environments are most useful. For now, I will close this issue as completed, because there is no `postqf` error involved.

**Comment by dominicraf** [comment]
Info about `pipx` available [here](https://pipx.pypa.io/stable/), you might mention it as an easy alternative if there are problems installing using `pip`.

**Comment by rseichter** [comment]
Thanks, I am aware of `pipx`. In the scenario of running `postqf`, pipx is at least as much overkill as Python's own `venv`, but the latter is at least an integral part of modern Python versions. My home-grown installation script is quite enough.
